// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
// This source code was auto-generated by Web Services Description Language Utility
//Mono Framework v2.0.50727.1433
//


/// <remarks/>
[System.Web.Services.WebServiceBinding(Name="FreeFoodMainSoap", Namespace="http://freefood.zedmaster.com.br/FreeFood")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class FreeFoodMain : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetServerVersionOperationCompleted;
    
    public FreeFoodMain() {
        this.Url = "http://localhost:8080/FreeFood.asmx";
    }
    
    public event GetServerVersionCompletedEventHandler GetServerVersionCompleted;
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://freefood.zedmaster.com.br/FreeFood/GetServerVersion", RequestNamespace="http://freefood.zedmaster.com.br/FreeFood", ResponseNamespace="http://freefood.zedmaster.com.br/FreeFood", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public string GetServerVersion() {
        object[] results = this.Invoke("GetServerVersion", new object[0]);
        return ((string)(results[0]));
    }
    
    public System.IAsyncResult BeginGetServerVersion(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetServerVersion", new object[0], callback, asyncState);
    }
    
    public string EndGetServerVersion(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    public void GetServerVersionAsync() {
        this.GetServerVersionAsync(null);
    }
    
    public void GetServerVersionAsync(object userState) {
        if ((this.GetServerVersionOperationCompleted == null)) {
            this.GetServerVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServerVersionCompleted);
        }
        this.InvokeAsync("GetServerVersion", new object[0], this.GetServerVersionOperationCompleted, userState);
    }
    
    private void OnGetServerVersionCompleted(object arg) {
        if ((this.GetServerVersionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetServerVersionCompleted(this, new GetServerVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
}

public partial class GetServerVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetServerVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

public delegate void GetServerVersionCompletedEventHandler(object sender, GetServerVersionCompletedEventArgs args);
